# Generated by Django 5.1.15 on 2026-09-04 18:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='deal title')),
                ('stage', models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=20, verbose_name='stage')),
                ('previous_stage', models.CharField(blank=True, choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20, null=True, verbose_name='previous stage')),
                ('value', models.DecimalField(decimal_places=2, help_text='Deal value in exact currency amount.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='deal value')),
                ('expected_close_date', models.DateField(db_index=True, verbose_name='expected close date')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='companies.company', verbose_name='company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_deals', to=settings.AUTH_USER_MODEL, verbose_name='deal owner')),
            ],
            options={
                'verbose_name': 'deal',
                'verbose_name_plural': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer')], default='CONTRIBUTOR', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_collaborators', to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'deal collaborator',
                'verbose_name_plural': 'deal collaborators',
                'unique_together': {('deal', 'user')},
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborating_deals', through='deals.DealCollaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('STAGE_CHANGE', 'Stage Changed'), ('REOPENED', 'Reopened'), ('OWNER_REASSIGNED', 'Owner Reassigned'), ('COLLABORATOR_ADDED', 'Collaborator Added'), ('COLLABORATOR_REMOVED', 'Collaborator Removed'), ('UPDATED', 'Updated')], default='STAGE_CHANGE', max_length=50)),
                ('from_stage', models.CharField(blank=True, choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20, null=True)),
                ('to_stage', models.CharField(blank=True, choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='notes / reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='deals.deal', verbose_name='deal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'deal history entry',
                'verbose_name_plural': 'deal history entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage', 'expected_close_date'], name='deals_deal_stage_723738_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['owner', 'stage'], name='deals_deal_owner_i_529a42_idx'),
        ),
    ]
