# Generated by Django 5.1.15 on 2026-09-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='company name')),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='industry')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='website')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='is archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'is_archived'], name='companies_c_name_556561_idx'), models.Index(fields=['owner', 'is_archived'], name='companies_c_owner_i_e3d02d_idx')],
            },
        ),
    ]
