# Generated by Django 5.1.15 on 2026-09-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PAST_DUE', 'Past Due Expected Close')], default='PAST_DUE', max_length=50)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False, verbose_name='is dismissed')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='dismissed at')),
                ('last_expected_close_date', models.DateField(blank=True, null=True, verbose_name='last seen expected close date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='deals.deal', verbose_name='deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_alerts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'deal alert',
                'verbose_name_plural': 'deal alerts',
                'ordering': ['-created_at'],
                'unique_together': {('deal', 'user', 'alert_type')},
            },
        ),
    ]
